field: 02422068-461a-4ae8-b733-076bb1a22d75
fieldLayouts:
  4b4f954c-cf92-40e4-b4c9-0862e2c893ea:
    tabs:
      -
        elements:
          -
            fieldUid: 0c72e31d-e683-499d-bbff-b2c3e8a6622f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c72e31d-e683-499d-bbff-b2c3e8a6622f:
    contentColumnType: string
    fieldGroup: null
    handle: sectionContent
    instructions: ''
    name: 'Section Content'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 783ea84a-08e4-49a1-87a4-d5277a8c8937
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fd8fa12b-0f22-4fe7-b6c9-db9322abab77
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_sectioncontent}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: callToAction
name: 'Call to Action'
sortOrder: 2
