fieldLayouts:
  34df236a-2c6a-4437-91d6-542a7bea9bf4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 43c544aa-79c0-41d7-a516-2dd9e2b56d1c
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f72ff5e-cb94-45b8-9c14-3ef04a86a875
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: da6cc147-e416-4622-acf8-ae9185d8f529
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 87249730-1c8b-4b1e-a8ec-d88386f73aa0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: services
name: Services
siteSettings:
  975b61b7-7678-4e53-9d19-ab12192c66e9:
    hasUrls: true
    template: services/entry
    uriFormat: 'services/{slug}'
structure:
  maxLevels: null
  uid: 31b876ac-3e71-4a00-be3f-2c5eb94a91f2
