fieldLayouts:
  4b5d3767-7f3e-4da4-baea-87cecbeee28f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 3be2861e-e49c-4039-b761-12af5f4cefb4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: gallery
hasUrls: true
name: Gallery
settings:
  path: '@webroot/uploads/images/big-images'
sortOrder: 4
type: craft\volumes\Local
url: /uploads/images/big-images
