contentColumnType: text
fieldGroup: 68752381-aca8-48a6-a9c9-9fab8af1ea54
handle: aboutUs
instructions: ''
name: 'About Us'
searchable: true
settings:
  byteLimit: null
  charLimit: 300
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
