contentColumnType: text
fieldGroup: 68752381-aca8-48a6-a9c9-9fab8af1ea54
handle: copyright
instructions: ''
name: Copyright
searchable: true
settings:
  byteLimit: null
  charLimit: 100
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
