contentColumnType: text
fieldGroup: cdac4bb0-6723-4166-b9dd-a27834a46669
handle: description
instructions: 'Add a short description for this entry. Content for this field will be used for page listings and SEO.'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: 250
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
