field: 04fe9a7e-7028-4835-aa7b-b1aef604b2a8
fieldLayouts:
  7f9ebc62-ebf8-4172-818d-7f834b50c26a:
    tabs:
      -
        elements:
          -
            fieldUid: d19bdb75-9f53-4028-b95d-2dfec7b82085
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6347d7b2-39f0-4d17-a7ee-0cae537f3a68
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e6935a02-f226-4659-a80d-cbd98860d6c7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3da07926-ad06-43e5-b888-f6deec952419
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3da07926-ad06-43e5-b888-f6deec952419:
    contentColumnType: string
    fieldGroup: null
    handle: verticalAlignment
    instructions: ''
    name: 'Vertical Alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - align-self-start
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - align-self-center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - align-self-end
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  6347d7b2-39f0-4d17-a7ee-0cae537f3a68:
    contentColumnType: string
    fieldGroup: null
    handle: columnWidth
    instructions: ''
    name: 'Column Width'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Organic
            -
              - value
              - col-lg
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 12'
            -
              - value
              - col-md-12
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 11'
            -
              - value
              - col-md-11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 10'
            -
              - value
              - col-md-10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 9'
            -
              - value
              - col-md-9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 8'
            -
              - value
              - col-md-8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 7'
            -
              - value
              - col-md-7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 6'
            -
              - value
              - col-md-6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 5'
            -
              - value
              - col-md-5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - col-md-4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - col-md-3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - col-md-2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - col-md-1
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  d19bdb75-9f53-4028-b95d-2dfec7b82085:
    contentColumnType: text
    fieldGroup: null
    handle: columnContent
    instructions: ''
    name: 'Column Content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e6935a02-f226-4659-a80d-cbd98860d6c7:
    contentColumnType: string
    fieldGroup: null
    handle: contentAlignment
    instructions: ''
    name: 'Content Alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Align Left'
            -
              - value
              - text-left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Align Center'
            -
              - value
              - text-center
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Align Right'
            -
              - value
              - text-right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
