enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  975b61b7-7678-4e53-9d19-ab12192c66e9:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
